### ISSUE TITLE
no more ip4.sig?

### ISSUE THREAD

**Issue by dev-101** [CIDRAM/Exports#1]
Hi Maikuolan, I see there is no longer single ip4.sig file in the repository? I think it was actually more convenient and useful, now there are so many parts to synchronize. Can I ask you why you split it this way?

Thanks

**Comment by Maikuolan** [comment]
This is in preparation for changes that JamesC will be implementing with ZB Block 0.6.0, planned to be released in the near future. :-)

(JamesC doesn't have a GitHub account AFAIK, but I'll send them a link to this issue and ask them whether there's anything I should reply here on their behalf).

**Comment by dev-101** [comment]
Thanks for clarification. As I see, ip4_hosts.sig is the essential part, other parts are not that critical imho.
Anyway, who is JamesC? Isn't ZBB site down and no longer active?

**Comment by Maikuolan** [comment]
Spambot Security's forum is 100% defunct and abandoned (I've still got no idea whether Zap is even aware of it or not, for that matter), but JamesC (one of the members at SBS) has registered a new domain and set up a forum there, as means to continue providing support for ZB Block and continue development: __https://www.zb-block.net/zbf/__

*Edit: Try without the "www" if you get certificate warnings. I haven't had this problem, but I vaguely recall some other members mentioning an issue with this over there at some point.*

Though the community overall is much smaller in size than it was at SBS, a number of the older members from SBS have joined up at JamesC's new forum (which is useful, because some of them, I had zero way of contacting otherwise).

I'll likely continue providing support for these signature exports into the foreseeable future (no plans to stop at the moment anyhow, and it's less of a burden now that we've got a working script here to export CIDRAM signature files into the format needed by ZB Block automatically), but in terms of developing the actual working codebase for ZB Block in the future, that'll be JamesC (plus whoever else wants to join in and help out in that regard; i.e., I won't be touching it personally; I've got CIDRAM anyhow, for any shiny new WAF-related coding that I might want to try my hand at in the future). ^.^

**Comment by ZB-Block-JamesC** [comment]
I have to say, I am very disappointed in how this conversation was handled.

For one thing, **at no time in this conversation** did Maikuolan state that ZB-Block is "inactive" or "not maintained". In fact, he stated the **opposite** in his first response: "This is in preparation for changes that JamesC will be implementing with ZB Block 0.6.0, planned to be released in the near future."

So I ask, what is the basis of yesterday's edit to one of your blog entries? "However, you should consider using other similar **active and maintained** projects, such as CIDRAM, which partially covers ZB Block’s main functionality to block cloud services and spammers, but it is **a newer script, frequently updated,** and also comes in a form of simple WordPress plugin."

I went through my server logs, and found where you clicked through from Maikuolan's link to my site. You viewed the forum index, then took a casual look at the _ZBB 0.5+ Support_ area ... you did not view the _Downloads and Documentation_ area (the first subforum on the list), where I had posted ELEVEN ZBB-related updates since the start of 2018.

Furthermore, you made ZERO attempt to contact me: you did not use the Contact Us form on my site, you did not register on my site (in order to post where I might notice, or PM me directly). 

Yes, the forum on Spambot Security is currently down ... it has been up and down since the end of January. But if you had visited earlier in the month, you may have noticed [this post on 1 January 2018](http://webcache.googleusercontent.com/search?q=cache:M9Pf-UV84VAJ:www.spambotsecurity.com/http://www.spambotsecurity.com/forum/viewtopic.php%3Ff%3D16%26t%3D4387+&cd=6&hl=en&ct=clnk&gl=us) (courtesy of Google's cache), where I announced **my** update to Zap's 0.4.10a3. 

Zap had offered, not only on his own site but [also on SFS](https://www.stopforumspam.com/forum/viewtopic.php?pid=45728#p45728), to allow someone else to take over ZBB. But when I, and Maikuolan, and others made _multiple_ attempts to contact Zap, in order to secure his "blessing" or "approval" of my taking over ZBB development, _nobody_ could elicit Zap's response. **At some point, is it not reasonable to assume that Zap has no objection?**

I have since released ZBB 0.4.21, which fixes the very bug that SBS displays 12 hours each day:
https://zb-block.net/zbf/showthread.php?t=27

I also released ZBB 0.5 (current version is 0.5.2), which adds _some_ IPv6 functionality (admittedly not as much as MacMathan wanted, but better than none!), **plus** support for PHP7.x, Cloudflare, optional exit screens (as MOB requested from Zap long ago), and drop-in support for MacMathan's blocklists so that users would no longer need to manually edit their files.
0.5.0 announcement: https://zb-block.net/zbf/showthread.php?t=28
0.5.1 announcement: https://zb-block.net/zbf/showthread.php?t=63
0.5.2 announcement: https://zb-block.net/zbf/showthread.php?t=73

ZBB 0.6 is in alpha testing. **Among other things**, 0.6 will allow users to customize their exit screen and block reasons (allowing German-specific or French-specific sites to display block notices and reasons in their preferred language), allow users to block Facebook "link summaries" without affecting the link itself, and **separates the CIDR-based blocklist** (the ip4.sig file, which is ZBB 0.5's evolution of badhosts.inc and badip.inc from Zap's code) **so that users can allow ISPs and/or proxies in without sacrificing their protection** from server farms and questionable webhosts. 

This particular repository **is** Maikuolan's separated CIDR-based blocklists for ZBB 0.6. He needed to adjust his scripts' output, I needed sample blocklists to test my code against. Maikuolan told you this, in not so many words, in his first response to this issue. 

So again, I ask: **on what basis** do you declare ZB-Block to be "unsupported" and "not actively maintained"?

**Comment by DanielRuf** [comment]
CIDRAM is actively developed from the ground up. ZBBlock is sporadically maintained in some way. Other solutions are much further and actively supported by their creators. You can just really maintain code that you know or have written.

**Comment by DanielRuf** [comment]
I'll lock this conversation for now as this is not helpful. Other users switched to other solutions which is their decision.
